# Generated by Django 5.0.3 on 2024-05-21 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('bidang', models.CharField(max_length=255)),
                ('telepon', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('tanggal_lahir', models.DateField()),
                ('kelas', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manajemen.guru')),
            ],
        ),
    ]
